### ISSUE TITLE
Add "data" (inline) as possible property of a resource

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/schemas#20]
See: http://dataprotocols.org/data-packages/index.html#inline-data

Also, add as "anyOf" required property.

**Comment by vitorbaptista** [comment]
FYI, there's a partial fix for this at https://github.com/dataprotocols/schemas/tree/add-inline-data

**Comment by danfowler** [comment]
Resolved by https://github.com/frictionlessdata/schemas/commit/cdc10cd2ef73e9efb0a82ef9749a29e93d4d201e
