### ISSUE TITLE
The URL in this repository description is broken

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/schemas#30]
http://schemas.datapackages.org/registry.csv doesn't exist anymore.

**Comment by pwalsh** [comment]
?

It has never existed. I only created the proxy for that domain yesterday, and started on the changes here in a dedicated branch yesterday, which I have not yet submitted as a PR, as well: https://github.com/dataprotocols/schemas/tree/feature/schemas.datapackages.org

**Comment by danfowler** [comment]
I believe this can be closed as the URLs exist:

http://schemas.frictionlessdata.io/registry.csv
http://schemas.datapackages.org/registry.csv
