### ISSUE TITLE
How to represent a long integer in json-table-schema?

### ISSUE THREAD

**Issue by pmackay** [frictionlessdata/schemas#47]
The definition of `number` and `integer` both do not seem sufficient to express a long integer in http://dataprotocols.org/json-table-schema/#number. Can anyone suggest how that should be done? I'm not sure the default constraints cover this.

**Comment by danfowler** [comment]
Hi @pmackay can you re-open this issue on https://github.com/frictionlessdata/specs/issues

This repo only holds the [JSON Schemas](http://json-schema.org/) that reflect the Frictionless Data specifications.  The repo for the specifications themselves are at https://github.com/frictionlessdata/specs/

**Comment by roll** [comment]
Thanks @pmackay - I've moved it to the `specs` issues tracker - https://github.com/frictionlessdata/specs/issues/277

**Comment by pmackay** [comment]
@roll thanks, sorry for not responding sooner.

**Comment by roll** [comment]
@pmackay oh no worries)

**Comment by danfowler** [comment]
@pmackay no worries x2
