### ISSUE TITLE
Outdated JSON Table Schema definitions (two files)

### ISSUE THREAD

**Issue by glarrain** [frictionlessdata/schemas#48]
- JST field type `duration` is not in `json-table-schema.json` but it was added to the spec on Nov 19, 2015 @ 1.0.0-pre10 (see https://github.com/frictionlessdata/specs/issues/210)
- JST field type `null` is in `definitions.json` but it was removed from the spec on May 19, 2016 @ 1.0.0-pre13 (see https://github.com/dataprotocols/dataprotocols/issues/262)

As a side note: I do not mean to be rude but these are pretty severe bugs. If this repo is really a
> [..] registry, for the Data Package family of specifications.

and these specifications are to be taken seriously (in the sense that people and organizations rely on them to do their work), it just can't have this kind of inconsistencies.

**Comment by danfowler** [comment]
@glarrain Hi, thanks very much for flagging.  We'll get these schema definitions updated.

**Comment by danfowler** [comment]
Thanks again @glarrain for pointing these issues out.

Closed by https://github.com/frictionlessdata/schemas/commit/4763adfdb7e213bab2528011f1282ccca21d8841
